stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/features
    params:
    - feature_engineering.max_features
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/features
    - models/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - reports/metrics.json